### ISSUE TITLE
Access app assets 

### ISSUE THREAD

**Issue by iBeef** [albo1337/flutter_full_pdf_viewer#10]
Hi,

First things first, love this plugin. It's by far the best plugin for pdfs available.

I'm not sure if it's my inexperience but is there a way to access a pdf in the app assets opposed to having to download the file everytime? I've tried a few things but cannot get it to work reliably.

Thanks.

**Comment by tsun424** [comment]
@iBeef , as I know, you cannot access assets directly, one solution is moving files from app asset to device local disk, then you should be able to access the files on local device.

**Comment by albo1337** [comment]
as @tsun424 mentioned already this is not that easy to implement. Sorry, but we can add the enhancement label so we have the possibility to rethink later. 

Thanks and have a nice week

**Comment by iBeef** [comment]
Hi,

Your suggestion worked, I loaded the asset and saved it to the applications doc directory and then can access it there.

Thanks fort he help.

**Comment by albo1337** [comment]
I'm going to close this ticket then. Thank you and have a nice day!

**Comment by ali-thowfeek** [comment]
> Hi,
> 
> Your suggestion worked, I loaded the asset and saved it to the applications doc directory and then can access it there.
> 
> Thanks fort he help.

For anyone wondering how to do this see,
https://stackoverflow.com/questions/54427646/load-pdf-file-custom-file-from-flutter-assets
