### ISSUE TITLE
Download pdf android and ios 

### ISSUE THREAD

**Issue by devfadl** [albo1337/flutter_full_pdf_viewer#17]
is there any availability to add download pdf file

**Comment by tlueder** [comment]
You can use other plugins for that, like:

https://pub.dartlang.org/packages/dio

response = await dio.download("https://www.google.com/", "./xx.html");

**Comment by l-k22** [comment]
> You can use other plugins for that, like:
> 
> https://pub.dartlang.org/packages/dio
> 
> response = await dio.download("https://www.google.com/", "./xx.html");

Then add the download button to your appbar

**Comment by devfadl** [comment]
> You can use other plugins for that, like:
> 
> https://pub.dartlang.org/packages/dio
> 
> response = await dio.download("https://www.google.com/", "./xx.html");

Have you try to  download cached pdf file ?

**Comment by tlueder** [comment]
I'm not sure what do you mean by "download cached pdf file". But I use this lib to sync pdf files between my app and a DAM.

**Comment by devfadl** [comment]
> I'm not sure what do you mean by "download cached pdf file". But I use this lib to sync pdf files between my app and a DAM.

i mean i save pdf files in directory in application from my app ,then i need user can view these files and can download or share them

**Comment by tlueder** [comment]
ok, that is exactly my use case.

As I wrote before. my app downloads files from a server backend to the local app directory, shows thumbnail to the user and if a user clicks on a pdf I use this lib to show the pdf

**Comment by devfadl** [comment]
> ok, that is exactly my use case.
> 
> As I wrote before. my app downloads files from a server backend to the local app directory, shows thumbnail to the user and if a user clicks on a pdf I use this lib to show the pdf

but  in my case application already have the file so i view it using  flutter_full_pdf_viewer , but i need to add feature to download it so user can share it throw other apps 
when using 
https://pub.dartlang.org/packages/dio

 i need to add url but i think it dosen't work with local files 
so you use url or local file path ?

**Comment by tlueder** [comment]
If your app already has the files, you don't need to download them.

have a look at this

https://github.com/tlueder/flutter-share

and use it with

https://pub.dartlang.org/packages/path_provider
