### ISSUE TITLE
Can't update to the version 1.0.4

### ISSUE THREAD

**Issue by Den-Ree** [albo1337/flutter_full_pdf_viewer#19]
Hello,
I got stuck with updating the package to the latest version. 

1. On version 1.0.3 there is an error 

```
error: property 'pageNumber' not found on object of type 'FlutterFullPdfViewerPlugin *'; did you mean to access instance variable 'pageNumber'?
        return self.pageNumber; 
```

2. The version 1.0.4 is not published:
```
Because the app depends on flutter_full_pdf_viewer ^1.0.4 which doesn’t match any versions, version solving failed.
pub get failed (1)
```

**Comment by l-k22** [comment]
If you go to the package page you will see it still on v1.0.3 https://pub.dartlang.org/packages/flutter_full_pdf_viewer
Not sure how long it takes for it to update

**Comment by Den-Ree** [comment]
@l-k22  thank you for the reply, but don't you know why it shows error with _pageNumber_ if use version 1.0.3?

**Comment by l-k22** [comment]
> @l-k22 thank you for the reply, but don't you know why it shows error with _pageNumber_ if use version 1.0.3?

There were some changes made by another programmer but their work was not checked before merge. https://github.com/albo1337/flutter_full_pdf_viewer/issues/16#issuecomment-469264309

**Comment by Den-Ree** [comment]
@l-k22 got it, thanks, will wait for the last release..

**Comment by albo1337** [comment]
Has the update work for you guys?

**Comment by Den-Ree** [comment]
@albo1337  1.0.3 no, we are waiting for 1.0.4, for now, we have downgraded to 1.0.2

**Comment by ezmegy** [comment]
Note: you can also do this while 1.0.4 arrives.

flutter_full_pdf_viewer:
    git:
      url: https://github.com/albo1337/flutter_full_pdf_viewer.git

**Comment by Den-Ree** [comment]
@ezmegy thank you) it works)

**Comment by ezmegy** [comment]
Great! ;)

Don't forget to check from time to time though, you might want to switch back to the "officially" published dartlang version at some stage. (E.g. with 1.0.4 as mentioned)

**Comment by albo1337** [comment]
Please check again. There went something wrong the first time. WTF! Sorry guys really!
