### ISSUE TITLE
App bar not shown correctly

### ISSUE THREAD

**Issue by dwhub** [albo1337/flutter_full_pdf_viewer#21]
When opening a pdf with AppBar somehow it's not showed correctly, it's like it being truncated.

<img width="443" alt="screen shot 2019-03-06 at 12 31 48 pm" src="https://user-images.githubusercontent.com/45648767/53858314-443acc00-400c-11e9-9c97-ab6904aff651.png">

I'm using iPhone 7 plus emulator.

**Comment by l-k22** [comment]
share some code please. Is the debugger returning any errors?

**Comment by dwhub** [comment]
@l-k22  - actually this is my bad.. I accidentally put the pdf viewer scaffold inside a scaffold.

the code is like this:
`  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        image: DecorationImage(
            image: AssetImage("assets/background.jpg"), fit: BoxFit.fill)),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          title: Text(""),
        ),
        body: FutureBuilder(
          future: FileServerRepository().downloadFile(widget.pdfPath) ,
          builder: (BuildContext context, AsyncSnapshot snapshot) {
            if (snapshot.hasData) {
              if (snapshot.data!=null) {
                return PDFViewerScaffold(
                  appBar: AppBar(),
                  path: snapshot.data
                );
              }
            } else {
                return CircularProgressIndicator();
              }
          }
        )
      )
    );
  }`

Removing the parent scaffold fixed the issue. sorry for the trouble.
