### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by l-k22** [albo1337/flutter_full_pdf_viewer#3]
My app isn't throwing any exceptions, I'm simply calling. Testing on Android x86 Nexus 5 Emulator
```
return new FutureBuilder(
        future: _presenter.downloadPDF(),
        builder: (BuildContext context, AsyncSnapshot snapshotURL) {
          if (!snapshotURL.hasData) {
            return new Center(
                child: new LoadingIndicator(Constants.msgLoading));
          } else {
            print("PDF path: ${snapshotURL.data}"); //"file:///$documentsdirectory/${file.name}/example.pdf"
            return new Center(
                child: new PDFViewerScaffold(
              appBar: AppBar(title: Text(' PDF'), actions: <Widget>[
                IconButton(icon: Icon(Icons.home), onPressed: () {}),
              ]),
              path: '${snapshotURL.data}',
            ));
          }
        });
```

**Comment by l-k22** [comment]
After upgrading my installation I am receiving errors. It returns FileNotFoundException
I know the file exists because I can see it in Device Explorer and I know I pointing to it correctly because I can open html files stored in the same directory. I have also tried accessing the file directly from the server.

**Comment by Xbobo5530** [comment]
I am getting a similar error, here is my stacktrace
### Log
```
E/PDFView (12929): load pdf error
E/PDFView (12929): java.io.FileNotFoundException: No such file or directory
E/PDFView (12929): 	at android.os.Parcel.openFileDescriptor(Native Method)
E/PDFView (12929): 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:270)
E/PDFView (12929): 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
E/PDFView (12929): 	at com.github.barteksc.pdfviewer.source.FileSource.createDocument(FileSource.java:37)
E/PDFView (12929): 	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
E/PDFView (12929): 	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
E/PDFView (12929): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
E/PDFView (12929): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/PDFView (12929): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/PDFView (12929): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/PDFView (12929): 	at java.lang.Thread.run(Thread.java:818)
```
I'm running this on a Nexus 5 running Android 6.0
### Visuals
The app only displays a black white screen
I've also tried different pdf URLs to check if its a faulty URL, but it still doesn't work
### Version
I'm running version `flutter_full_pdf_viewer: ^1.0.2`

**Comment by albo1337** [comment]
Could you use version 1.0.1 and test it again?

**Comment by Xbobo5530** [comment]
Okay...
I'll get back to you with the feedback

--
Paul Sean
Operations
nyayozangu.com
Nyayo Zangu Init Co. Ltd.

**Comment by Xbobo5530** [comment]
@albo1337 Hey, so i tried something else, I noticed I had added an `initialData: ''` value to my `FutureBuilder`, I guess this caused it to try and create a local file with a `url` `''`, I am guessing this is what caused the `pdf error`.
It works now after removing it and listening for the `snapshot.data` and waiting for the the `snapshot` actually has `data`.
Maybe you can include a better error message like `bad url` or something like that so its easier to dig out the bug...
Thanks for the support
