### ISSUE TITLE
ndk filters causes flutter to make only a "armeabi-v7a" version

### ISSUE THREAD

**Issue by Saifallak** [albo1337/flutter_full_pdf_viewer#40]
by following this https://github.com/albo1337/flutter_full_pdf_viewer/blob/master/README.md#4-informations-for-release-on-android

cases flutter only to make armeabi-v7a only in appbundle

**Comment by KorbinianMossandl** [comment]
you need to add all the abis to that list that your app should support. so if you only add "armeabi-v7a" it will only support that.
```

            ndk {
                abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            }
```
this should do for most devices, if you need others just add them.

**Comment by Saifallak** [comment]
okay thanks, this should be mentioned in [README.MD](https://github.com/albo1337/flutter_full_pdf_viewer/blob/master/README.md)

**Comment by Roshanalexander** [comment]
@Saifallak Could it also mean that it only supports armeabi-v7a?

**Comment by Saifallak** [comment]
Idk, sorry. My project was canceled and never used this package since that.
