### ISSUE TITLE
iOS Side Should Be Using WkWebview

### ISSUE THREAD

**Issue by inkrh** [albo1337/flutter_full_pdf_viewer#43]
In the iOS 12 SDK, UIWebView has been officially deprecated in favor of WKWebView, Apple first advised against using UIWebView in iOS 8 - https://developer.apple.com/documentation/webkit/wkwebview?language=objc. 

Flutter Full PDF Viewer currently still uses UIWebView:

https://github.com/albo1337/flutter_full_pdf_viewer/blob/master/ios/Classes/FlutterFullPdfViewerPlugin.m

**Comment by jeroentrappers** [comment]
Yes, I got this as well while submitting to the app store.

> Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by jeroentrappers** [comment]
https://github.com/albo1337/flutter_full_pdf_viewer/pull/44

**Comment by albo1337** [comment]
merged it. Jeroen could you maybe update the pub files and upload a new version to pub?

**Comment by albo1337** [comment]
Updated everytihing. Version 1.0.5 is the newest version now

**Comment by jeroentrappers** [comment]
Thank you for the quick response!

**Comment by jeroentrappers** [comment]
I'm looking into it, if you have any ideas, pleas share ;-)

**Comment by jeroentrappers** [comment]
Fix in most recent pull request.

**Comment by albo1337** [comment]
I will publish the new version later guys. Are you 100% sure that it works now jeroen?




Holen Sie sichOutlook für Android







On Fri, Sep 13, 2019 at 12:28 PM +0200, "Jeroen Trappers" <notifications@github.com> wrote:












Fix in most recent pull request.

**Comment by jeroentrappers** [comment]
I've just tested it on my test-device. It works. However to be sure, it should be tested on multiple devices. 

to test you can simply put this in your pubspec.yaml

flutter_full_pdf_viewer:
    git:
      url: git://github.com/jeroentrappers/flutter_full_pdf_viewer

**Comment by KingLudwig94** [comment]
just tested on my device, it works well. 
Thank you for the fix.

**Comment by albo1337** [comment]
Allrighr i will merge the request and publish a now version today evening. Thank you a lot Jeroen! 




Holen Sie sichOutlook für Android







On Fri, Sep 13, 2019 at 12:54 PM +0200, "KingLudwig94" <notifications@github.com> wrote:












just tested on my device, it works well.

Thank you for the fix.

**Comment by albo1337** [comment]
new version 1.0.6 is out now. Please test again and give me feedback guys. If its working, I'll close this ticket. Thank you a lot for all your help

**Comment by inkrh** [comment]
Thanks @albo1337
