### ISSUE TITLE
I want to overlay PDF view with some buttons...

### ISSUE THREAD

**Issue by squeezeboxhuf** [albo1337/flutter_full_pdf_viewer#49]
But I'm struggling to achieve this using a Stack like this:

```
Stack(children: [
              PDFViewerScaffold(
                 path: _filePath,
              ),
              OutlineButton(
                child: Text("Back"),
                onPressed: () {
                  Navigator.pop(context);
                },
              ),
              OutlineButton(
                child: Text("Next"),
                onPressed: () {
                  print("next clicked!)");
                },
              ),
            ])
```
but I'm not seeing the buttons... Can anyone enlighten me please?

Thanks.

**Comment by laxian** [comment]
I have the similar problem. I wan't to show a modal bottom sheet over pdf view,
but the PDF view is always on the top.

**Comment by squeezeboxhuf** [comment]
> I have the similar problem. I wan't to show a modal bottom sheet over pdf view,
> but the PDF view is always on the top.

Yes, I found the same too! I don't want to have to navigate away each time I want to change a user parameter.

**Comment by Ahmadre** [comment]
I can tell you why: The developer of this plugin uses the WebKit and WebViews of the platforms and these are native code, so it will overlay over Flutter 😞

**Comment by laxian** [comment]
> > I have the similar problem. I wan't to show a modal bottom sheet over pdf view,
> > but the PDF view is always on the top.
> 
> Yes, I found the same too! I don't want to have to navigate away each time I want to change a user parameter.

Use Platform View instead

**Comment by w4mxl** [comment]
> > > I have the similar problem. I wan't to show a modal bottom sheet over pdf view,
> > > but the PDF view is always on the top.
> > 
> > 
> > Yes, I found the same too! I don't want to have to navigate away each time I want to change a user parameter.
> 
> Use Platform View instead

Could you elaborate on the situation with Platform View ? Thanks.

**Comment by laxian** [comment]
> > > > I have the similar problem. I wan't to show a modal bottom sheet over pdf view,
> > > > but the PDF view is always on the top.
> > > 
> > > 
> > > Yes, I found the same too! I don't want to have to navigate away each time I want to change a user parameter.
> > 
> > 
> > Use Platform View instead
> 
> Could you elaborate on the situation with Platform View ? Thanks.

Try this plugin：[pdf_viewer_plugin](https://pub.dev/packages/pdf_viewer_plugin).
I hope it helps for you.
