### ISSUE TITLE
Exmaple is deprecated / old and not working anymore

### ISSUE THREAD

**Issue by Ahmadre** [albo1337/flutter_full_pdf_viewer#52]
Your provided example in: https://github.com/albo1337/flutter_full_pdf_viewer/blob/master/example/lib/main.dart

is very old and I don't know how to use your plugin :(! On pub.dev you also have nowhere any docs! 

Could please tell the world how to use this?

Thx

**Comment by Ahmadre** [comment]
Ok, sorry I didn't read your example fully. I found what I wanted. Thx

**Comment by maurobotta** [comment]
Demo don't work in Flutter Web

**Comment by MoacirSchmidt** [comment]
It seems that flutter_full_pdf_viewer is not web compatible yet? Congratulations and much thanks for your great solution!
