### ISSUE TITLE
bottomNavigationBar is destroyed after using PdfViewerScaffold

### ISSUE THREAD

**Issue by Ahmadre** [albo1337/flutter_full_pdf_viewer#54]
After I integrated your plugin and test it on the iPhone 11 Pro I'll get following error with my bottomnavigationbar:

<img width="377" alt="Bildschirmfoto 2019-11-30 um 16 53 15" src="https://user-images.githubusercontent.com/18512224/69902845-5460bb80-1392-11ea-87b3-335502ae3df0.png">

Before opening the plugin it's all ok, but after once i opened a pdf this happens 😢

**Comment by Ahmadre** [comment]
Please have a look:
![Bildschirmvideo-aufnehmen-2019-11-30-um-19 01 28-Wiederhergestellt](https://user-images.githubusercontent.com/18512224/69905111-d57a7b80-13af-11ea-8fd3-23af17c598a2.gif)

**Comment by Ahmadre** [comment]
Alright: Solved it by:

```dart
    Scaffold(
          resizeToAvoidBottomInset: false,
    ...
    );
```

on both Scaffolds (upper where BottomNavigationBar is and on the child where the wiki page is)

**Comment by premtemp1** [comment]
Sorry. I know this is close but I have the same issue .. Is the solution to wrap the PDFViewerScaffold with a Scaffold?
